# Generated by Django 5.0.3 on 2024-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="acquired_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="maximum_speed",
            field=models.IntegerField(null=True),
        ),
    ]
